- packages/mds-daily/tools/metrics-sheet/index.js
Running Prettier/ESLint as part of the test suite results in formatting/linting changes to this file that were not included in the original commit. Pushing these changes so the file is no longer modified on every test run.
> Run ESLint/Prettier

- packages/mds-api-helpers/index.ts
- packages/mds-audit/src/api.ts
- packages/mds-provider/api.ts
- packages/mds-provider/package.json
- packages/mds-provider/tsconfig.json
> Helper functions for JSON API links and managing paging parameters

- packages/mds-agency/api.ts
- packages/mds-audit/src/api.ts
- packages/mds-audit/src/validators.ts
- packages/mds-audit/tests/validators.spec.ts
- packages/mds-daily/api.ts
- packages/mds-policy/api.ts
- packages/mds-provider/api.ts
- packages/mds-provider/event-processor/labelers/provider-labeler.ts
- packages/mds-providers/index.ts
> [mds-all] put providerName in a library and de-dup

- .vscode/launch.json
- packages/mds-audit/src/api.ts
- packages/mds-db/index.ts
- packages/mds-db/types.ts
- packages/mds-provider/api.ts
- packages/mds-provider/event-processor/index.ts
- packages/mds-provider/event-processor/labelers/device-labeler.ts
- packages/mds-provider/event-processor/labelers/provider-labeler.ts
- packages/mds-provider/event-processor/labelers/trip-labeler.ts
- packages/mds-provider/event-processor/processors/status-changes-processor.ts
- packages/mds-provider/event-processor/processors/trips-processor.ts
- packages/mds-provider/event-processor/types.ts
- packages/mds-provider/package.json
- packages/mds-provider/types.ts
- packages/mds-stream/index.ts
All the provider event processing is still inactive, but wanted to get some of this reviewed/merged and kept current with recent changes to master.
> [mds-provider] More updates to event processing

- .eslintrc.js
- .vscode/settings.json
- packages/mds-db/index.ts
- packages/mds-provider/api.ts
- packages/mds-provider/event-processor/index.ts
- packages/mds-provider/event-processor/labelers/device-labeler.ts
- packages/mds-provider/event-processor/labelers/provider-labeler.ts
- packages/mds-provider/event-processor/labelers/trip-labeler.ts
- packages/mds-provider/event-processor/processors/status-changes-processor.ts
- packages/mds-provider/event-processor/processors/trips-processor.ts
- packages/mds-provider/event-processor/types.ts
- packages/mds-stream/index.ts
- types/mds.d.ts
More updates to the provider event processing to include processing db events that predate the provider event stream.
> [mds-provider] Updated Event Processing

- .pre-commit-config.yaml
- package.json
- yarn.lock
> [mds-*] Add pre-commit with basic hooks for added security

- aws-lambda/mds-agency/package.json
- packages/mds-agency/package.json
- packages/mds-compliance/package.json
Bump agency version to reflect recent changes (e.g. new services areas)
> [mds-agency] Bump agency version

- packages/mds-cache/index.ts
- packages/mds-cache/unflatteners.ts
- packages/mds-daily/api.ts
> [mds-daily] [mds-cache] Optimize /admin/vehicle_counts endpoint

- packages/mds-cache/index.ts
> [mds-cache] Fix missing curly

- packages/mds-utils/index.ts
Noticed a discrepancy between the code and the state diagrams.
> [mds-utils] [mds-agency] Consider available -> trip transition valid

- packages/mds-daily/api.ts
- packages/mds-daily/tools/metrics-sheet/geo-metrics.js
- packages/mds-daily/tools/metrics-sheet/index.js
Add 48hr filter for area counts.
- [ x ] simple searchable title - `[mds-db] Add PG env var`, `[config] Fix eslint config`
- [ x ] briefly describe the changes in this PR
> Add 48hr filter for area counts

- packages/mds-agency/api.ts
Instead of reading all device_ids to verify proper provider when POSTing an event, read the device and check for matching provider_id.
> [mds-agency] Optimize POST event query

- packages/mds-db/index.ts
> [mds-agency] Clean up logs

- package.json
- packages/mds-agency/api.ts
- packages/mds-agency/tests/test.ts
- packages/mds-api-server/index.ts
- packages/mds-api-server/package.json
- packages/mds-api-server/tests/index.spec.ts
- packages/mds-api-server/tsconfig.json
- packages/mds-audit/src/api.ts
- packages/mds-audit/tests/api.spec.ts
- packages/mds-compliance/tests/api.spec.ts
- packages/mds-daily/api.ts
- packages/mds-daily/tests/test.ts
- packages/mds-db/index.ts
- packages/mds-policy/api.ts
- packages/mds-policy/tests/api.spec.ts
- packages/mds-provider/api.ts
- packages/mds-provider/tests/test.ts
Implementing a standard `health` endpoint for all APIs.
> Standard health endpoint

- packages/mds-compliance/tests/api.spec.ts
- packages/mds-policy/api.ts
- packages/mds-policy/tests/api.spec.ts
- types/mds.d.ts
> [mds][mds-policy] Add provider ids to policy

- packages/mds-agency/api.ts
> [mds-agency] JSON.stringify err object

- packages/mds-db/index.ts
> [mds-db] Change warn to info to stop spamming Slack

- packages/mds-logger/index.ts
- packages/mds-logger/tests/test.ts
> [mds-*] never log '[object Object]'

- packages/mds-agency/api.ts
- packages/mds-db/index.ts
> [mds-agency] Improve error handling when POSTing a vehicle

- packages/mds-db/index.ts
> [mds-db] Refactor writeEvent to async/await

- .eslintrc.js
- package.json
- packages/mds-agency/api.ts
- yarn.lock
> [mds-*] Add promise linter rules, and clean up half of agency

- packages/mds-db/index.ts
- packages/mds-db/sql-utils.ts
- packages/mds-db/tests/migration.spec.ts
Marking as `mds-*` because the db underlies all the services
> [mds-*] finish removing 'new Promise' from mds-db

- packages/mds-db/index.ts
> [mds-db] Add useWriteable param to readDevice to mitigate race condition for device registration

- packages/mds-agency/api.ts
- packages/mds-agency/tests/test.ts
- packages/mds-db/index.ts
return a 400 and add'l error info if no new telemetry was sent
> [mds-agency] detect all-redundant telemetry

- aws-lambda/aws-serverless-express-handler/index.ts
- aws-lambda/webpack.config.js
- package.json
- packages/mds-api-server/index.ts
- packages/mds-api-server/tests/index.spec.ts
- yarn.lock
Adds a build property to AWS lambdas. This information can be viewed with `GET /`
```
{
"name": "@aws-lambda/mds-audit",
"version": "0.1.4",
"build": {
"branch": "master",
"commit": "671bb6e"
},
"node": "10.15.3"
}
```
> [mds-*] Add branch/commit to build info

- packages/mds-db/index.ts
- packages/mds-provider/event-processor/index.ts
- packages/mds-utils/exceptions.ts
> Improve provider query performance

- packages/mds-compliance/api.ts
- packages/mds-policy/api.ts
- packages/mds-policy/tests/api.spec.ts
> [mds-compliance] [mds-policy] Transition to async/await

- packages/mds-logger/tests/test.ts
> [mds-logger] Fix mds-logger tests

- aws-lambda/aws-serverless-express-handler/index.ts
- aws-lambda/mds-agency/server.ts
- aws-lambda/mds-audit/server.ts
- aws-lambda/mds-compliance/server.ts
- aws-lambda/mds-daily/server.ts
- aws-lambda/mds-native/server.ts
- aws-lambda/mds-policy/server.ts
- aws-lambda/mds-provider/server.ts
- packages/mds-agency/server.ts
- packages/mds-agency/tests/test.ts
- packages/mds-api-server/index.ts
- packages/mds-api-server/tests/index.spec.ts
- packages/mds-audit/server.ts
- packages/mds-audit/tests/api.spec.ts
- packages/mds-compliance/server.ts
- packages/mds-compliance/tests/api.spec.ts
- packages/mds-daily/server.ts
- packages/mds-daily/tests/test.ts
- packages/mds-native/server.ts
- packages/mds-native/tests/api.spec.ts
- packages/mds-policy/server.ts
- packages/mds-policy/tests/api.spec.ts
- packages/mds-provider/server.ts
- packages/mds-provider/tests/test.ts
Initialize server outside of handler function. Also, rename to avoid some conflicts.
> Refactor lambda express server

- packages/mds-api-server/index.ts
- packages/mds-api-server/tests/index.spec.ts
Adding build version info to the `/health` response
> [mds-core] Add build info to /health response

- packages/mds-cache/index.ts
- packages/mds-provider/utils.ts
- yarn.lock
> [mds-provider] Add legacy provider events back

- packages/mds-provider/utils.ts
- packages/mds-types/index.ts
Provider `event_type_reason` should be `user_pick_up` not `trip_start`
> FIx provider event_type_reason

- package.json
- packages/ladot-service-areas/package.json
- packages/mds-cache/package.json
- packages/mds-daily/package.json
- packages/mds-db/package.json
- packages/mds-logger/package.json
- packages/mds-policy/package.json
- packages/mds-stream/package.json
- packages/mds-types/package.json
Some packages had incorrect `license` properties.
> Fix license fields

- packages/mds-compliance/api.ts
- packages/mds-providers/index.ts
> [mds-compliance] More compliance scoping

- packages/mds-metrics-sheet/metrics-log.ts
Add `status` specifications to the sheet, per the `event_type` -> `vehicle_status` in MDS.
> [mds-metrics-sheet] Add `status` reporting to Google Metrics Sheet

- packages/mds-metrics-sheet/metrics-log.ts
> Fix import that breaks bundle

- packages/mds-agency/api.ts
- packages/mds-db/index.ts
> [mds-agency][mds-db] Fix vehicles endpoint to read from DB instead of cache

- packages/mds-policy/api.ts
> [mds-policy] Remove excessive logs

- packages/mds-agency/api.ts
- packages/mds-compliance/api.ts
- packages/mds-provider/api.ts
- packages/mds-stream/index.ts
First round of security audit changes, mostly makes logging more informative / consistent.
> [logger] Security audit fixes

- packages/mds-policy-author/api.ts
- packages/mds-policy/api.ts
> [mds-policy] [mds-policy-author] Add CORS header for policy and policy-author APIs

- packages/mds-compliance/mds-compliance-engine.ts
- packages/mds-types/index.ts
> [mds-compliance] Update compliance API to conform with spec

- packages/mds-compliance/mds-compliance-engine.ts
- packages/mds-compliance/tests/api.spec.ts
> [mds-compliance] Fix compliance maximum 0 evaluation, and add test case to explicitly exercise that behavior. Thanks javascript <3

- packages/mds-agency/api.ts
- packages/mds-agency/tests/test.ts
- packages/mds-api-authorizer/package.json
- packages/mds-api-authorizer/tests/index.spec.ts
- packages/mds-api-server/index.ts
- packages/mds-api-server/tests/index.spec.ts
- packages/mds-audit/api.ts
- packages/mds-audit/tests/api.spec.ts
- packages/mds-compliance/api.ts
- packages/mds-compliance/tests/api.spec.ts
- packages/mds-daily/api.ts
- packages/mds-daily/package.json
- packages/mds-daily/tests/test.ts
- packages/mds-native/api.ts
- packages/mds-native/tests/api.spec.ts
- packages/mds-policy-author/api.ts
- packages/mds-policy-author/tests/api.spec.ts
- packages/mds-policy/api.ts
- packages/mds-policy/tests/api.spec.ts
- packages/mds-provider/api.ts
- packages/mds-provider/tests/test.ts
- packages/mds-test-data/index.ts
The /test/ endpoints are unneeded, as we can access fixtures from within the test suite directly.
> [mds-core] Remove /test/ endpooints.

- packages/mds-api-authorizer/package.json
> [mds-api-authorizer] Reduce coverage a little more

- packages/mds-compliance/api.ts
Return whenever a response code is sent to express.
> [mds-compliance] Add return keyword to all res.sends

- .github/PULL_REQUEST_TEMPLATE.md
- packages/mds-native/api.ts
- packages/mds-native/tests/api.spec.ts
- packages/mds-native/types.ts
- packages/mds-policy/server.ts
> [mds-native] Minor code changes to match spec updates

- .vscode/launch.json
- packages/mds-policy-author/package.json
> Fix API unit tests when running in debugger

- aws-lambda/mds-agency/package.json
- aws-lambda/mds-audit/package.json
- aws-lambda/mds-compliance/package.json
- aws-lambda/mds-daily/package.json
- aws-lambda/mds-metrics-sheet/package.json
- aws-lambda/mds-native/package.json
- aws-lambda/mds-policy-author/package.json
- aws-lambda/mds-policy/package.json
- aws-lambda/mds-provider/package.json
> Point deployment scripts at new develop environment instead of dev3

- packages/mds-compliance/mds-compliance-engine.ts
- packages/mds-db/index.ts
- packages/mds-types/index.ts
Also a minor fix to a bad import in mds-db.
> [mds-compliance] [mds-db] For each vehicle considered in violation, add the first rule_id it was seen in violation of.

- packages/mds-policy-author/api.ts
- packages/mds-policy-author/tests/api.spec.ts
> [mds-policy-author] Removing unnecessary date params for now.

- packages/mds-provider/legacy.ts
- packages/mds-providers/index.ts
Switched LADOT to a recognized provider_id. Also update latency warning threshold for provider status changes.
> Update recognized provider_id list

- packages/mds-daily/api.ts
- packages/mds-daily/db-helpers.ts
- packages/mds-daily/request-handlers.ts
- packages/mds-daily/tests/db-helpers.test.ts
- packages/mds-daily/tests/request-handlers.test.ts
- packages/mds-daily/tests/test.ts
- packages/mds-daily/tests/utils.test.ts
- packages/mds-daily/types.ts
- packages/mds-daily/utils.ts
*DRAFT* Don't merge yet
Refactor + improve tests
I moved a bunch of stuff around, so we should probably
also write some Cypress tests for this to make sure
we don't break anything.
- [ X] simple searchable title - `[mds-db] Add PG env var`, `[config] Fix eslint config`
- [X ] briefly describe the changes in this PR
- [ X] Daily
> Improve test coverage on [mds-daily]

- packages/mds-audit/api.ts
- packages/mds-audit/tests/api.spec.ts
> [mds-audit] Manually set /vehicles/ paging params for audit, and remove relevant tests.

- packages/mds-compliance/mds-compliance-engine.ts
- packages/mds-compliance/tests/api.spec.ts
- packages/mds-compliance/tests/engine-test.spec.ts
- packages/mds-types/index.ts
> [mds-compliance] Finalize implementation of speed rule compliance

- packages/mds-compliance/api.ts
- packages/mds-compliance/tests/engine-test.spec.ts
> [mds-compliance] Fix build
