CityOfLosAngeles/mds-core

packages/mds-agency/api.ts
packages/mds-agency/tests/test.ts
packages/mds-audit/tests/api.spec.ts
packages/mds-compliance/tests/api.spec.ts
packages/mds-daily/tests/test.ts
packages/mds-policy/tests/api.spec.ts
packages/mds-provider/tests/test.ts
packages/mds-test-data/index.ts

Found a bunch of places where we had legacy strings.  Replaced.  No new tests.

[mds-all] uniformly use VEHICLE_TYPES and PROPULSION_TYPES in tests

---

packages/mds-compliance/api.ts
packages/mds-compliance/tests/api.spec.ts
packages/mds-db/index.ts
packages/mds-db/types.ts
packages/mds-test-data/index.ts

This PR adds the ability to specify an `end_date` in a request to the `compliance/snapshot` endpoint, to enable historical lookup. Easy possible extension of this could be adding an optional `start_date` parameter as well, for more accurate reconstruction.

[mds-compliance] [mds-db] Add support for historical Compliance Snapshots

---

aws-lambda/aws-serverless-express-handler/index.ts
aws-lambda/aws-serverless-express-handler/tests/index.spec.ts
aws-lambda/mds-daily/server.ts
packages/mds-agency/api.ts
packages/mds-agency/package.json
packages/mds-agency/types.ts
packages/mds-api-authorizer/index.ts
packages/mds-api-authorizer/tests/index.spec.ts
packages/mds-api-server/index.ts
packages/mds-audit/src/api.ts
packages/mds-audit/tests/api.spec.ts
packages/mds-audit/tests/validators.spec.ts
packages/mds-compliance/api.ts
packages/mds-compliance/package.json
packages/mds-compliance/types.ts
packages/mds-daily/api.ts
packages/mds-daily/package.json
packages/mds-daily/server.ts
packages/mds-daily/types.ts
packages/mds-policy/api.ts
packages/mds-policy/package.json
packages/mds-policy/types.ts
packages/mds-provider/api.ts
packages/mds-provider/tests/test.ts

Each API implemented its own authorization header parser. Converted APIs to utilize the standard authorizer claims provided by `mds-api-authorizer` and `mds-api-server and removed of all the various and largely redundant `getAuth` functions.

[mds-api-server] Remove redundancy using standard authorizer claims

---

packages/mds-db/index.ts
packages/mds-db/migration.ts
packages/mds-db/schema.ts
packages/mds-db/types.ts
packages/mds-provider/api.ts
packages/mds-provider/event-processor/index.ts
packages/mds-provider/event-processor/labelers/device-labeler.ts
packages/mds-provider/event-processor/labelers/provider-labeler.ts
packages/mds-provider/event-processor/labelers/trip-labeler.ts
packages/mds-provider/event-processor/processors/status-changes-processor.ts
packages/mds-provider/event-processor/processors/trips-processor.ts
types/mds.d.ts

By guaranteeing query order (recorded IDX + PK), we can use the existing `skip/take` parameters to reliably poll for new status changes without the need for an additional sequencing mechanism.

[mds-provider] remove sequence column

---

packages/mds-compliance/api.ts

Don't throw an error when a device is in DB and not in cache when computing realtime compliance snapshots.

[mds-compliance] Remove error throw

---

packages/mds-agency/api.ts
packages/mds-agency/tests/test.ts
packages/mds-db/tests/mds-db.spec.ts
packages/mds-provider/tests/test.ts
packages/mds-test-data/index.ts

Northbound Provider and other feeds should include a `register` event, per spec, but we will add that as part of the registration rather than asking providers to send a separate event

[mds-agency][mds-provider] add register event

---

packages/mds-stream/index.ts

Restrict the number of entries maintained in the `device:raw` stream

Reduce device:raw stream cap

---

packages/mds-cache/index.ts
packages/mds-db/index.ts
packages/mds-db/schema.ts
packages/mds-logger/index.ts

While we should be using named exports, this PR simply replaces `export =` with the `export default` ... module consumption remains unchanged.

Use default export for services

---

package.json

In order to use mds-core as a library, the importing module needs access to mds-core build artifacts under `dist` for each package.  But those build artifacts are not published anywhere at this time.
Short of publishing mds-core to a package registry, this PR implements the solution of using a `prepare` script to tell the importing library to build mds-core on install and put the build artifacts into node_modules/mds-core alongside the src.
A side effect of `prepare` is that it also gets run after every `yarn install` within mds-core.
In addition, a `files` include is used to workaround a yarn bug in which the prepare lifecycle script is not run for a git hosted dependency.
https://github.com/yarnpkg/yarn/issues/5235#issuecomment-490019287

[mds-*] support build on install

---

aws-lambda/aws-utils/index.ts
packages/mds-agency/api.ts
packages/mds-cache/index.ts
packages/mds-db/sql-utils.ts
packages/mds-logger/index.ts

Move KMS object creation out of the decrypt() call, so it'll only be one per lambda
Change log.{info|warn|error} to use more sensible signature of `any[]`
Switch bad-event from `warn` to `info` to reduce slack spam

[mds-*] reduce kms file handle consumption

---

aws-lambda/aws-serverless-express-handler/index.ts
aws-lambda/webpack.config.js
packages/mds-api-server/index.ts

Adding the build date to the About (`/`) endpoint response:
```
{
"name": "@aws-lambda/mds-audit",
"version": "0.1.4",
"build": {
"date": "2019-07-23T15:20:46.971Z",
"branch": "master",
"commit": "605ce1b"
},
"node": "10.15.3"
}
```
Presently, the `build` property is not available when running locally. Will look at improving that subsequently.

Add build date to about endpoint

---

packages/mds-api-server/index.ts
packages/mds-api-server/tests/index.spec.ts
yarn.lock

Allow setting a `MAINTENANCE` environment variable to put an API in maintenance mode which will cause it to respond to all requests with `503 - Service Unavailable`
`MAINTENANCE=Database Migration` response to _ALL requests_:

[mds-api-server] API Maintenance Mode

---

packages/mds-cache/index.ts
packages/mds-compliance/mds-compliance-engine.ts
packages/mds-compliance/tests/api.spec.ts
packages/mds-compliance/tests/engine-test.spec.ts
packages/mds-types/index.ts

Instead of allowing overflow within a rule's "bucket", force all overflow (vehicles which matched the rule\'s criteria but could not fit in the rule\'s bucket) to cascade down throughout the rule evaluation. At the end of the policy evaluation, all vehicles which have overflowed and never fit in a bucket will be considered violations.

[mds-compliance] Rework Count Rule Measurement

---

.talismanrc
packages/mds-cache/index.ts

[mds-cache] Switch a log.warn to log.info to avoid spamming slack for a cache miss

---

aws-lambda/mds-agency/package.json
aws-lambda/mds-audit/package.json
aws-lambda/mds-compliance/package.json
aws-lambda/mds-daily/package.json
aws-lambda/mds-native/package.json
aws-lambda/mds-policy/package.json
aws-lambda/mds-provider/package.json
package.json
packages/mds-agency/api.ts
packages/mds-agency/package.json
packages/mds-audit/package.json
packages/mds-compliance/package.json
packages/mds-daily/package.json
packages/mds-logger/index.ts
packages/mds-logger/package.json
packages/mds-metrics-sheet/metrics-log.ts
packages/mds-metrics-sheet/package.json
packages/mds-metrics-sheet/vehicle-counts.ts
packages/mds-native/package.json
packages/mds-policy/package.json
packages/mds-provider/package.json

I noticed a few places in the code (metrics sheets and logger) were doing `require('dotenv').config()`. Preloading is generally the preferred approach because this method of setting environment variables is typically only used during development. `.env` files are generally not recommended in CI/CD or Production.
Also, removed some legacy npm scripts that are no longer functional.

Favor command line over require('dotenv') in code

---

.talismanrc
packages/mds-cache/index.ts

[mds-cache] Instead of attempting to look up the provider_id, simply provider it as a function param.

---

.talismanrc
packages/mds-db/index.ts

Don't automatically create tables and run migrations unless the environment variable `PG_MIGRATIONS` is `'true'`. This allows some control over when (and via which API) migrations are run.

[mds-db] Control automatic migrations with env var

---

packages/mds-provider/tests/status-changes.spec.ts
packages/mds-provider/utils.ts

The `Agency` to `Provider` mapping of the service_end event is being modified such that the resulting vehicle state is more consistent.

Change service_end provider event mapping

---

packages/mds-api-server/index.ts
packages/mds-api-server/tests/index.spec.ts
packages/mds-audit/api.ts
packages/mds-audit/tests/api.spec.ts

Added a new middleware function that can be used to restrict access to endpoints by scope. Also, showed an example of how this is used.

Express middleware to verify access via scopes

---

aws-lambda/api-gateway-authorizer/index.ts
aws-lambda/api-gateway-authorizer/package.json
container-images/env-inject/tsconfig.build.json
packages/mds-api-authorizer/index.ts
packages/mds-audit/api.ts
tsconfig.json

These are the changes required to extract a user's email from an API access token custom claim and also to support multiple valid audiences. The changes should be backwards compatible with existing Auth0 APIs, M2M tokens, and other application tokens. The plan is to deploy these changes to a new authorizer lambda and repoint API Gateway in addition to creating new scoped Auth0 APIs. Then we can request applications to switch to using the API audience for the new scoped APIs and switch Compliance Mobile to use API access tokens rather than ID tokens for accessing the API.

[mds-audit] Get authenticated user's email from a custom claim

---

packages/mds-agency/api.ts

Agency should require a provider_id. There was an extraneous if condition that would allow access to agency endpoints without a valid provider_id. A recent change to our authorizers brought this issue to light. TypeScript FTW.

[mds-agency] No access without valid provider ID

---

packages/mds-native/api.ts
packages/mds-utils/tests/validators.spec.ts
packages/mds-utils/validators.ts

Treating strings as numbers can lead to unpredictable results.

Convert numeric query string parameters before type guarding

---

packages/mds-metrics-sheet/metrics-log.ts
packages/mds-metrics-sheet/package.json
packages/mds-metrics-sheet/tests/mds-metrics-sheet.test.ts
packages/mds-metrics-sheet/types.ts

This should squash this lambda log error:
2019-09-18T07:00:45.559Z 0c7fca82-d644-4985-8b37-15cbcd440f5e ERROR ERROR getProviderMetrics TypeError: Cannot read property 'trip_enter' of undefined
Testing plan:
1. Run test suite
- [ X] simple searchable title - `[mds-db] Add PG env var`, `[config] Fix eslint config`
- [ X] write tests for all new functionality

[mds-metrics-sheet] Adds optional type to metrics event_counts_last_24h

---

bin/install
helm/dashboard/Chart.yaml
helm/dashboard/templates/kubernetes-dashboard.yaml
helm/dashboard/templates/service-account.yaml

* (un)install:metricsAdapter
* banzaicloud-stable/kube-metrics-adapter named kube-metrics-adapter in the namespace kub-system
* ability to vary mds-namespace
* eg '% ./bin/install -c:namespace-mds=foo install:mds
* better documentation/usage-message for install:fallbackCertificate,ingressGatewayCertificate
* as they both require additional configs (ie domain and key/cert path respectively)
* support discreet install:namespace=a,b,c operation
* noting: at present bin/install uses namespace existence as a pre-install guard
* make dashboard work again
* make cli:[postgresql,redis] work again

installer: +metrics-adapter, vary mds-namespace, more docs, discreet ns ops

---

bin/image-build
container-images/mds-agency/package.json
container-images/mds-audit/package.json
container-images/mds-compliance/package.json
container-images/mds-daily/package.json
container-images/mds-metrics-sheet/package.json
container-images/mds-native/package.json
container-images/mds-policy-author/package.json
container-images/mds-policy/package.json
container-images/mds-provider/package.json

Moves the docker build command from `package.json` to a utility script, so that we can check the current branch and suffix the container image tag as needed.

suffix the container image tag based on the current git branch

---

bin/install

provide the ability to install tiller cluster provisioning capabilities when needed, eg: gcp
test:
`% ./bin/install ... install:tiller ...`

install: conditionally install tiller cluster role
